# Theory Questions

***1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?***

Ans. NumPy (Numerical Python) is a library that adds support for large, multi-dimensional arrays and matrices, along with a wide range of high-performance mathematical functions to operate on them. Its purpose is to provide an efficient and flexible way to perform numerical computations, making it a fundamental package for scientific computing and data analysis in Python.

Here are some advantages of numpy
1. Efficient array operations: NumPy's array-based computations are much faster than Python's built-in lists.
2. Vectorized operations: Perform operations on entire arrays at once, reducing loops and improving performance.
3. Multi-dimensional arrays: Easily work with 2D, 3D, and higher-dimensional data.
4. Matrix operations: Supports advanced linear algebra functions, like matrix multiplication and decomposition.
5. Random number generation: High-quality random number generators for simulations and modeling.

Enhancing Python's capabilities:

1. Speed: NumPy's optimized C code accelerates numerical computations.
2. Convenience: Simplifies array and matrix operations, reducing code complexity.
3. Flexibility: Supports various data types, including integers, floats, and complex numbers.
4. Advanced functions: Provides specialized functions for signal processing, statistics, and more.



***2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?***


Ans. NumPy provides two functions for calculating the average of an array: np.mean() and np.average(). While they seem similar, there are key differences:

np.mean()

- Calculates the arithmetic mean (average) of the array elements.
- Ignores NaN (Not a Number) values.
- Weights all elements equally.

Example

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

mean_value = np.mean(arr)
print(mean_value)

3.0


np.average()

- Calculates the weighted average of the array elements.
- Allows specifying weights for each element.
- Supports axis specification for multi-dimensional arrays.
- Raises a warning if NaN values are present (unless weights are provided).

Example:



In [ ]:
arr = np.array([1, 2, 3, 4, 5])
weights = np.array([0.1, 0.2, 0.3, 0.2, 0.2])

avg_value = np.average(arr, weights=weights)
print(avg_value)

3.2


Choose np.mean() when:

- You need a simple arithmetic mean.
- NaN values are present and should be ignored.

Choose np.average() when:

- You need a weighted average.
- You want to specify axis for multi-dimensional arrays.
- You want to handle NaN values explicitly.


***3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.***

Ans. NumPy provides several methods to reverse an array along different axes:

1. np.flip(): Reverses the order of elements along the specified axis.

2. np.flipud(): Reverses the order of elements along the vertical axis (axis 0).

3. np.fliplr(): Reverses the order of elements along the horizontal axis (axis 1).

4. arr[::-1]: Reverses the entire array using slicing.

Examples:

1D Array:

arr = np.array([1, 2, 3, 4, 5])

- np.flip(arr): [5, 4, 3, 2, 1]
- arr[::-1]: [5, 4, 3, 2, 1]



In [ ]:
arr = np.array([1, 2, 3, 4, 5])
np.flip(arr)


array([5, 4, 3, 2, 1])

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr[::-1]


array([5, 4, 3, 2, 1])

2D Array:


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.fliplr(arr)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [ ]:
np.flipud(arr)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
arr[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

***4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance***

Ans. To determine the data type of elements in a NumPy array, use the dtype attribute:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

int64


Data types are crucial in memory management and performance:



1. Memory Usage: Different data types occupy varying amounts of memory. Choosing the appropriate data type can significantly reduce memory usage.



1. Performance: Operations on arrays with smaller data types are generally faster than those with larger data types.



***5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?***

Ans. ndarrays (n-dimensional arrays) are the core data structure in NumPy, providing efficient storage and operations for multi-dimensional data.

Key Features:

1. Multi-dimensional: ndarrays can have any number of dimensions (axes).
2. Homogeneous: All elements must be of the same data type.
3. Fixed-size: ndarrays have a fixed shape and size.
4. Fast operations: ndarrays support vectorized operations, making them much faster than standard Python lists.
5. Memory-efficient: ndarrays store data in a contiguous block of memory.

Differences from standard Python lists:

1. Data type: ndarrays require a uniform data type, while lists can store mixed types.
2. Memory layout: ndarrays store data contiguously, while lists store pointers to individual elements.
3. Operations: ndarrays support vectorized operations, while lists require loops or list comprehensions.
4. Speed: ndarrays are significantly faster for numerical computations.

Let's see examples of ndarray vs list.

In [ ]:
my_list = [1, 2, 3, 4, 5]

my_arr = np.array([1, 2, 3, 4, 5])

In [ ]:
my_list

[1, 2, 3, 4, 5]

In [ ]:
my_arr

array([1, 2, 3, 4, 5])

In [ ]:
#let's do multiplication
my_arr*2 # in ndarray there is vactorisation for doing computation that makes it easy, fast and hasle free

array([ 2,  4,  6,  8, 10])

In [ ]:
#in list we have to use iteration
list1 = []
for i in my_list:
  list1.append(i*2)
list1

[2, 4, 6, 8, 10]

***6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.***

Ans. NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to:

1. Vectorized Operations: NumPy arrays enable vectorized operations, allowing operations to be applied to entire arrays at once, reducing loops and improving performance.

2. Memory Efficiency: NumPy arrays store data in a contiguous block of memory, reducing memory allocation and deallocation overhead.

3. Cache Locality: NumPy arrays optimize cache usage, minimizing memory access times.

4. Compiled C Code: NumPy's core operations are implemented in compiled C code, providing a significant speed boost.

5. Parallelization: NumPy arrays can leverage multi-core processors for parallelized operations.

Benchmarking Example:






In [ ]:
import time
# Large-scale numerical operation: Element-wise multiplication

Python list time: 0.11126947402954102


In [ ]:
# Python list
python_list = list(range(1000000))
start_time = time.time()
result_list = [x * 2 for x in python_list]
end_time = time.time()
print("Python list time:", end_time - start_time)


Python list time: 0.10044169425964355


In [ ]:
# NumPy array
numpy_array = np.arange(1000000)
start_time = time.time()
result_array = numpy_array * 2
end_time = time.time()
print("NumPy array time:", end_time - start_time)

NumPy array time: 0.01799631118774414


Here we can clearly see that Numpy array is faster than python list.

***7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.***

vstack() and hstack() are NumPy functions used to stack arrays vertically and horizontally, respectively.

vstack()

- Stacks arrays vertically (row-wise).
- Concatenates arrays along the vertical axis (axis 0).
- Resulting array has the same number of columns as the input arrays.

Example:







In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
np.vstack((arr1, arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

hstack()

- Stacks arrays horizontally (column-wise).
- Concatenates arrays along the horizontal axis (axis 1).
- Resulting array has the same number of rows as the input arrays.

Example:




In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
np.hstack((arr1, arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

***8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.***

Ans. fliplr() and flipud() are NumPy methods used to flip arrays horizontally and vertically, respectively.

fliplr()

- Flips the array horizontally (left-right).
- Reverses the order of columns (axis 1).
- Leaves rows (axis 0) unchanged.

flipud()

- Flips the array vertically (up-down).
- Reverses the order of rows (axis 0).
- Leaves columns (axis 1) unchanged.

Effects on array dimensions:

- Both fliplr() and flipud() reverse the order of elements doesn't shows error on 1D dimension because it works only when if m.ndim < 2.
- 2D array:
    - fliplr(): Reverses column order, leaving row order unchanged.
    - flipud(): Reverses row order, leaving column order unchanged.
- 3D array:
    - fliplr(): Reverses column order (axis 1), leaving row (axis 0) and depth (axis 2) orders unchanged.
    - flipud(): Reverses row order (axis 0), leaving column (axis 1) and depth (axis 2) orders unchanged.

Examples:



In [ ]:
# 1D array
arr = np.array([1, 2, 3, 4, 5])

print(np.fliplr(arr))
print(np.flipud(arr))





ValueError: Input must be >= 2-d.

In [ ]:
# 2D array
arr = np.array([[1, 2], [3, 4]])
arr


array([[1, 2],
       [3, 4]])

In [ ]:
np.fliplr(arr)

array([[2, 1],
       [4, 3]])

In [ ]:
np.flipud(arr)

array([[3, 4],
       [1, 2]])

In [ ]:
# 3D array
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
np.fliplr(arr)

array([[[3, 4],
        [1, 2]],

       [[7, 8],
        [5, 6]]])

In [ ]:
np.flipud(arr)

array([[[5, 6],
        [7, 8]],

       [[1, 2],
        [3, 4]]])

***9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?***

Ans. The array_split() method in NumPy splits an array into multiple sub-arrays along a specified axis. It is useful for dividing data into smaller chunks for processing or analysis.

Functionality:

- Splits an array into n sub-arrays along the specified axis.
- Returns a list of sub-arrays.

Syntax:

numpy.array_split(ary, n, axis=0)

Parameters:

- ary: Input array.
- n: Number of sub-arrays to split into.
- axis: Axis along which to split (default=0).

Handling Uneven Splits:

When the array length is not exactly divisible by n, array_split() distributes the remaining elements as evenly as possible among the sub-arrays.

Example:


In [ ]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.array_split(arr, 3, 0)


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

***10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?***

Ans. Vectorization and broadcasting are fundamental concepts in NumPy that enable efficient array operations.

Vectorization:

Vectorization refers to the ability to perform operations on entire arrays at once, without the need for explicit loops. NumPy's vectorized operations apply the operation element-wise to each element in the array.

Example:


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr * 2


array([ 2,  4,  6,  8, 10])

Broadcasting:

Broadcasting allows NumPy to perform operations on arrays with different shapes and sizes by aligning and replicating elements as needed.

Example:


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr1 + arr2


array([5, 7, 9])

# Practical Questions

***1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.***

In [ ]:
np.random.randint(1,100,(3,3))

array([[81, 88, 54],
       [58, 68, 45],
       [11,  6,  5]])

***2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array***

In [ ]:
arr_1d = np.arange(10)
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_1d.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr_1d.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

***3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.***

In [2]:
import numpy as np
a = np.random.rand(4,4)
a

array([[0.98904276, 0.01920014, 0.41593664, 0.66190187],
       [0.70200219, 0.68582135, 0.83008636, 0.86954904],
       [0.59700943, 0.38416112, 0.52458931, 0.85298381],
       [0.29455209, 0.74469472, 0.5419317 , 0.76281705]])

In [3]:
b = np.zeros((6,6))
b

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
b[1:-1,1:-1] = a
b

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.98904276, 0.01920014, 0.41593664, 0.66190187,
        0.        ],
       [0.        , 0.70200219, 0.68582135, 0.83008636, 0.86954904,
        0.        ],
       [0.        , 0.59700943, 0.38416112, 0.52458931, 0.85298381,
        0.        ],
       [0.        , 0.29455209, 0.74469472, 0.5419317 , 0.76281705,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

***4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.***

In [6]:
np.arange(10,60,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

***5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element***

In [7]:
a = np.array(['python', 'numpy', 'pandas'])
a

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [11]:
b= np.char.upper(a)
b

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [12]:
np.char.lower(b)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [13]:
np.char.title(a)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

***6. Generate a NumPy array of words. Insert a space between each character of every word in the array.***

In [14]:
a = np.array(['python', 'numpy', 'pandas'])
a

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [15]:
np.char.join(' ', a)

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

***7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division***

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
np.add(arr,2)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [19]:
np.subtract(arr,2)

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [20]:
np.multiply(arr,2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [21]:
np.divide(arr,2)

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5],
       [5. , 5.5, 6. ]])

***8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.***

In [22]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.diag(arr)

array([1., 1., 1., 1., 1.])

***9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.***

In [2]:
import numpy as np
arr = np.random.randint(0,1001,100)
arr

array([830, 920, 974, 398, 901,  81, 832, 504, 579, 743, 616, 508, 307,
       696, 512, 442, 180, 543, 994, 879, 512, 240, 188, 916, 434, 487,
       743, 623, 575, 240,  89, 956, 428, 517,  45, 324, 116, 681, 719,
       839, 744, 500, 735, 888, 175,  99, 119, 667, 692, 494, 732, 505,
       395, 635, 814, 637, 900, 506, 458, 627, 227, 772, 516,  87, 967,
       845, 251, 722, 406, 821, 908, 314, 932, 217, 834, 749, 872, 486,
       176, 142, 326, 281, 243, 243, 869, 158, 520, 258, 490, 701, 808,
       573, 927, 978, 830, 371, 436, 428, 100, 208])

In [3]:
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, n):
        if n % i == 0:
            return False
    return True

In [6]:
prime_numbers= arr[np.vectorize(is_prime)(arr)]
print(prime_numbers)


[743 307 487 743  89 719 839 227 967 251 821 281 701]


***10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.***


In [7]:
daily_temperatures = np.random.uniform(20, 30, 30)
daily_temperatures

array([21.30295025, 25.56568001, 22.82386329, 28.58484279, 23.61152914,
       25.7799817 , 25.24437269, 26.97223813, 27.05931022, 24.23764564,
       25.44633647, 28.91942757, 26.05293104, 21.81918939, 28.84466695,
       23.36927591, 27.52079072, 23.11861984, 28.18368298, 27.33455788,
       21.61740242, 23.28909884, 29.87577659, 20.15384789, 20.33136186,
       21.87282136, 28.02974023, 25.78670446, 29.55543478, 26.06548382])

In [11]:
# Here i excluded last two days because python cannot reshape 30 to 7
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)
weekly_temperatures

array([[21.30295025, 25.56568001, 22.82386329, 28.58484279, 23.61152914,
        25.7799817 , 25.24437269],
       [26.97223813, 27.05931022, 24.23764564, 25.44633647, 28.91942757,
        26.05293104, 21.81918939],
       [28.84466695, 23.36927591, 27.52079072, 23.11861984, 28.18368298,
        27.33455788, 21.61740242],
       [23.28909884, 29.87577659, 20.15384789, 20.33136186, 21.87282136,
        28.02974023, 25.78670446]])

In [12]:
last_two_days = daily_temperatures[28:]
last_two_days

array([29.55543478, 26.06548382])

In [15]:
weekly_averages = np.mean(weekly_temperatures, axis=1)
print(weekly_averages)

[24.70188855 25.78672549 25.71271381 24.19133589]
